<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/3/28
 * Time: 15:17
 */
namespace app\admin\controller;

use app\common\model\Admin as AdminModel;
use app\common\model\Role;
use app\common\validate\AdminValidate;
use think\Lang;
use think\Request;
use think\Validate;

class Admin extends Adminbase{
    function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    //列表页
    function index() {
        $build_model = new AdminModel();
        $list = $build_model->paginate();

        $this->assign('list', $list);
        $page = $list->render();

        $this->assign('page', $page);
        return $this->fetch();
    }


    //添加
    function add() {
        if (!$this->request->isPost()) {
            $roles = Role::all();
            $this->assign('roles', $roles);
            return $this->fetch();
        } else {
            //表单验证
            $result = AdminValidate::validate($_POST);
            if ($result === true) {
                $admin_model = new AdminModel($_POST);
                if ($admin_model->allowField(true)->save()) {
                    $this->success(lang('success'), url('admin/index'));
                } else {
                    $this->error(lang('error'));
                }
            } else {
                $this->error($result);
            }
        }
    }

    //编辑
    function edit() {
        $id = input('param.id');
        if (!$id) {
            $this->error('parameter_error');
        }

        $admin = AdminModel::get($id);
        if (!$admin) {
            $this->error('parameter_error');
        }

        if (!$this->request->isPost()) {
            $roles = Role::all();
            $this->assign('roles', $roles);

            $this->assign('admin', $admin);
            return $this->fetch();
        } else {
            //表单验证
            $result = AdminValidate::validate($_POST);
            if ($result === true) {
                $_POST['username'] = $admin->username;


                if ($admin->allowField(true)->save($_POST, ['id'=>$id])) {
                    $this->success(lang('success'), url('admin/index'));
                } else {
                    $this->error(lang('error'));
                }
            } else {
                $this->error($result);
            }
        }
    }

    function del() {
        $id = input('param.id');
        if (!$id) {
            $this->error('parameter_error');
        }

        $admin = AdminModel::get($id);
        if (!$admin) {
            $this->error('parameter_error');
        }

        if ($admin->adminid == 1) {
            $this->error('该用户不能删除');
        }

        if ($admin->delete()) {
            $this->success(lang('delete_success'));
        }
        $this->error(lang('delete_error'));
    }
}
