<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018-11-6
 * Time: 22:33
 */
namespace app\admin\controller;

use app\common\validate\AdpositionValidate;
use think\facade\Lang;

class Adposition extends Adminbase{
    function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    function index() {
        if (!$this->request->isAjax()) {
            return $this->fetch();
        } else {
            $adposition_model = new \app\common\model\Adposition();
            $list = $adposition_model->order('position_id desc')->paginate()->toArray();
            $result = [];
            $result['code'] = 1;
            $result['msg'] = "";
            $result['count'] = $list['total'];
            $data = $list['data'];
            $result['data'] = $data;;
            echo json_encode($result);
        }
    }

    function add() {
        if (!$this->request->isAjax()) {
            return $this->fetch('adds');
        } else {
            $result = AdpositionValidate::validate($_POST);
            if ($result === true) {
                $adposition_model = new \app\common\model\Adposition();
                if ($adposition_model->allowField(true)->save($_POST)) {
                    $this->success(lang('success'), url('adposition/index'));
                } else {
                    $this->error(lang('error'));
                }
            } else {
                $this->error($result);
            }
        }
    }

    function edit() {
        $position_id = $this->request->param('position_id', 0, 'intval');
        if (!$position_id) {
            $this->error(lang('link_error'));
        }

        $position = \app\common\model\Adposition::get($position_id);
        if (!$position) {
            $this->error(lang('link_error'));
        }

        if (!$this->request->isAjax()) {
            $this->assign('position', $position);
            return $this->fetch();
        } else {
            $result = AdpositionValidate::validate($_POST);
            if ($result === true) {
                if (false !== $position->allowField(true)->save($_POST)) {
                    $this->success(lang('success'), url('adposition/index'));
                } else {
                    $this->error(lang('error'));
                }
            } else {
                $this->error($result);
            }
        }
    }

    function del() {
        if ($this->request->isAjax()) {
            $position_id = $this->request->param('position_id', 0, 'intval');
            if (!$position_id) {
                $this->error(lang('link_error'));
            }

            $position = \app\common\model\Adposition::get($position_id);
            if (!$position) {
                $this->error(lang('link_error'));
            }

            if ($position->ads) {
                $this->error(lang('has_ads'));
            }

            if ($position->delete()) {
                $this->success(lang('success'));
            } else {
                $this->error(lang('error'));
            }
        }
    }
}
