<?php
namespace app\admin\controller;

use think\Controller;

class Ajax extends Adminbase
{
    function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function loadGrade()
    {
        $school_id = $this->request->param('school_id', 0, 'intval');
        if (!$school_id) {
            $this->error(lang('link_error'));
        }

        $school_model = model('school');
        $school = $school_model->with('grades')->get($school_id)->toArray();
        $this->assign('grades', $school['grades']);
        $result = $this->fetch('grade');
        $this->result($result, '1', '数据初始化成功', 'json');
    }
}
