<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018-11-5
 * Time: 15:24
 */
namespace app\admin\controller;

//邮箱设置类
use app\common\model\MailerTemplate;
use app\common\model\Option;
use app\common\validate\MailerTemplateValidate;
use think\facade\Lang;

class Article extends Adminbase{
    function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    function index() {
        if (!$this->request->isAjax()) {
            return $this->fetch();
        } else {
            $ad_model = model('article');
            $where = [];
            $order = 'article_id desc';
            $paginate = $ad_model->where($where)->with('articleclass')->order($order)->paginate()->toArray();
            $result = [];
            $result['code'] = 1;
            $result['msg'] = "";
            $result['count'] = $paginate['total'];
            $result['data'] = $paginate['data'];
            echo json_encode($result);
            exit;
        }
    }


    function add() {
        if (!$this->request->isAjax()) {
            $classes = model('articleclass')->all();
            $this->assign('pid', 0);
            $this->assign('classes', $classes);
            return $this->fetch('adds');
        } else {
            $article_model = model('article');
            if ($article_model->allowField(true)->save($_POST)) {
                $this->success(lang('success'), url('article/index'));
            } else {
                $this->error(lang('error'));
            }
        }
    }

    function edit() {
        $article_id = $this->request->param('id', 0, 'intval');
        if (!$article_id) {
            $this->error(lang('link_error'));
        }

        $article_model = model('article');
        $article = $article_model->get($article_id);
        if (!$article) {
            $this->error('link_error');
        }

        if (!$this->request->isAjax()) {
            $classes = model('articleclass')->all();
            $this->assign('pid', $article['ac_id']);
            $this->assign('classes', $classes);

            $this->assign('article', $article);
            return $this->fetch();
        } else {
            if ($article->allowField(true)->save($_POST)) {
                $this->success(lang('success'), url('article/index'));
            } else {
                $this->error(lang('error'));
            }
        }
    }

    function load_template() {
        if ($this->request->isAjax()) {
            $template_code = $this->request->param('tpl', '', 'trim');
            $tpl = MailerTemplate::load_tpl($template_code);
            $this->success(lang('success'), '', $tpl);
        }
    }

    function del() {
        if ($this->request->isAjax()) {
            $template_id = $this->request->param('template_id', 0, 'intval');
            if (!$template_id) {
                $this->error(lang('link_error'));
            }

            $template = MailerTemplate::get($template_id);
            if (!$template) {
                $this->error(lang('link_error'));
            }

            if ($template->delete()) {
                $this->success(lang('success'));
            } else {
                $this->error(lang('error'));
            }
        }
    }

    function test() {
        sendMail('ucosxiu_x@163.com', 'user_register', '', '', ['user_name'=> 'uuuuu', 'register_code'=> '112345']);
    }
}
