<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018-11-5
 * Time: 15:24
 */
namespace app\admin\controller;

//邮箱设置类
use app\common\model\MailerTemplate;
use app\common\model\Option;
use app\common\validate\MailerTemplateValidate;
use think\facade\Lang;

class Comment extends Adminbase{
    function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    function index() {
        if (!$this->request->isAjax()) {
            return $this->fetch();
        } else {

            $comment_model = model('comment');
            $where = [];

            $order = 'comment_id desc';
            $paginate = $comment_model->where($where)->order($order)->paginate()->toArray();
            $result = [];
            $result['code'] = 1;
            $result['msg'] = "";
            $result['count'] = $paginate['total'];
            $result['data'] = $paginate['data'];
            echo json_encode($result);
            exit;
        }
    }


    function view() {
        $order_id = $this->request->param('id', 0, 'intval');
        if (!$order_id) {
            $this->error(lang('link_error'));
        }

        $order_model = model('order');
        $order = $order_model->with(['activity', 'school'])->get($order_id);
        if (!$order) {
            $this->error('link_error');
        }
        if (!$this->request->isAjax()) {
            $this->assign('order', $order);
            return $this->fetch();
        } else {

        }
    }

}
