<?php
namespace app\admin\controller;

use think\Controller;

class Index extends Adminbase
{
    function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        return $this->fetch();
    }
}
