<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019-3-25
 * Time: 15:08
 */

namespace app\admin\controller;


use think\db\Where;

class Member extends Adminbase
{
    function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    function index() {
        if (!$this->request->isAjax()) {
            return $this->fetch();
        } else {
            $member_model = model('member');
            $where = [];
            $is_vip = $this->request->param('is_vip', -1, 'intval');
            if ($is_vip != -1) {
                $where['is_vip'] = $is_vip;
            }
            $member_name = $this->request->param('member_name', '', 'trim');
            if ($member_name) {
                $where['member_name'] = ['like', '%' . $member_name.'%'];
            }

            $mobile = $this->request->param('mobile', '', 'trim');
            if ($mobile) {
                $where['mobile'] = ['like', '%' . $mobile.'%'];
            }
            $order = 'member_id';
            $paginate = $member_model->where(new Where($where))->order($order)->paginate()->toArray();
            $result = [];
            $result['code'] = 1;
            $result['msg'] = "";
            $result['count'] = $paginate['total'];
            $data = $paginate['data'];
            $result['data'] = $data;
            echo json_encode($result);
        }
    }

    function unbind() {
        $id = $this->request->param('id', 0, 'intval');
        if (!$id) {
            $this->error(lang('param_error'));
        }
        $member_model = model('member');
        $member = $member_model->get($id);

        if ($member->is_vip) {
            $vip_model = model('vip');
            $vip_model->where(['member_id' => $member->member_id])->update(['member_id' => 0]);
            $member->data(['is_vip' => 0])->save();

            $this->success('解绑成功');
        } else {
            $this->error(lang('param_error'));
        }
    }

    function status () {
        $id = $this->request->param('id', 0, 'intval');
        if (!$id) {
            $this->error(lang('param_error'));
        }
        $member_model = model('member');
        $member = $member_model->get($id);

        $status = $this->request->param('status', 0, 'intval');
        if ($member->data(['status' => $status])->save()) {
            $this->success(lang('success'));
        } else {
            $this->error(lang('error'));
        }
    }
}
