<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/3/27
 * Time: 9:34
 */
namespace app\admin\controller;

//后台菜单类
use app\common\model\Menu as MenuModel;
use app\common\validate\MenuValidate;
use think\Controller;
use think\facade\Lang;
use think\Request;
use think\View;

class Menu extends Adminbase{
    function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    //
    function index() {
        if ($this->request->isAjax()) {
            $categorys = \app\common\model\Menu::initTree();
            echo $this->success('', '', $categorys);
            exit;
        }
        return $this->fetch();
    }

    //添加
    function add() {
        $parentid = input('param.parentid');

        $options = \app\common\model\Menu::selectTree($parentid);

        if (!$this->request->isPost()) {
            $this->assign('options', $options);
            return $this->fetch('adds');
        } else {
            //表单验证
            $result = MenuValidate::validate($_POST);
            if ($result === true) {
                $muenu_model = new MenuModel($_POST);

                if ($muenu_model->allowField(true)->save()) {
                    $this->success(lang('success'), url('menu/index'));
                } else {
                    $this->error(lang('error'));
                }
            } else {
                $this->error($result);
            }
        }
    }

    //编辑
    function edit() {
        $id = input('param.id');
        if (!$id) {
            $this->error('parameter_error');
        }

        $menu = MenuModel::get($id);
        if (!$menu) {
            $this->error('parameter_error');
        }

        $options = \app\common\model\Menu::selectTree($menu->parentid);

        if (!$this->request->isPost()) {
            $this->assign('options', $options);
            $this->assign('_menu', $menu);
            return $this->view->fetch();
        } else {
            //表单验证
            $result = MenuValidate::validate($_POST);
            if ($result === true) {
                if (false !== $menu->allowField(true)->save($_POST, ['id'=>$id])) {
                    $this->success(lang('success'), url('menu/index'));
                } else {
                    $this->error(lang('error'));
                }
            } else {
                $this->error($result);
            }
        }

    }

    //删除
    function del() {
        $id = input('param.id');
        if (!$id) {
            $this->error('parameter_error');
        }

        $menu = MenuModel::get($id);
        if (!$menu) {
            $this->error('parameter_error');
        }

        $count = MenuModel::where('parentid',$id)->count();
        if ($count > 0) {
            $this->error(lang('sub_menu_exist'));
        }
        if ($menu->delete()) {
            $this->success(lang('success'));
        } else {
            $this->error(lang('error'));
        }
    }

    //排序
    function listorders() {
        $id = input('param.id', 0, 'intval');
        if (!$id) {
            $this->error('parameter_error');
        }

        $val = input('param.val', 0, 'intval');
        if (!$val) {
            $this->error('parameter_error');
        }

        if ($val > 10000 || $val < 0) {
            $this->error('parameter_error');
        }

        $menu_model = new MenuModel();
        $data['listorder'] = $val;
        $status = $menu_model->allowField(true)->save($data, ['menuid'=>$id]);

        if ($status !== false) {
            $this->success(lang('success'));
        } else {
            $this->error(lang('error'));
        }
    }

}
