<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/3/28
 * Time: 14:39
 */

namespace app\admin\controller;

use app\common\model\Admin;
use app\common\model\Role as RoleModel;
use app\common\validate\RoleValidate;
use think\Lang;

//角色类
class Role extends Adminbase{
    function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    //列表类
    function index() {
        if (!$this->request->isAjax()) {
            //获取所有分类
            return $this->fetch();
        } else {

            $role_model = new RoleModel();
            $paginate = $role_model->paginate()->toArray();

            $result = [];
            $result['code'] = 1;
            $result['msg'] = "";
            $result['count'] = $paginate['total'];
            $result['data'] = $paginate['data'];
            echo json_encode($result);
        }

    }

    //添加
    function add() {
        if (!$this->request->isPost()) {
            return $this->fetch();
        } else {
            //表单验证
            $result = RoleValidate::validate($_POST);
            if ($result === true) {
                $role_model = new RoleModel($_POST);

                if ($role_model->allowField(true)->save()) {
                    $this->success(lang('success'), url('activity/index'));
                } else {
                    $this->error(lang('error'));
                }
            } else {
                $this->error($result);
            }
        }
    }

    //编辑
    function edit() {
        $id = input('param.id');
        if (!$id) {
            $this->error('parameter_error');
        }

        $role = RoleModel::get($id);
        if (!$role) {
            $this->error('parameter_error');
        }

        if (!$this->request->isPost()) {
            $this->assign('role', $role);
            return $this->view->fetch();
        } else {
            //表单验证
            $result = RoleValidate::validate($_POST);
            if ($result === true) {
                if (false !== $role->allowField(true)->save($_POST, ['id'=>$id])) {
                    $this->success(lang('success'), url('activity/index'));
                } else {
                    $this->error(lang('error'));
                }
            } else {
                $this->error($result);
            }
        }
    }

    //删除
    function del() {
        $id = input('param.id');
        if (!$id) {
            $this->error('parameter_error');
        }

        $role = RoleModel::get($id);
        if (!$role) {
            $this->error('parameter_error');
        }

        $count = Admin::where('roleid',$id)->count();
        if ($count > 0) {
            $this->error(lang('admin_in_role_exist'));
        }

        if ($role->delete()) {
            $this->success(lang('success'));
        } else {
            $this->error(lang('error'));
        }
    }
}
